import { handleTableRequest, type TableRequestContext } from "../_table";

export async function onRequestGet(context: TableRequestContext): Promise<Response> {
  return handleTableRequest(context, {
    viewName: "v_order_items_canonical",
    defaultSortBy: "saleDate",
    defaultSortDir: "desc",
    sortableColumns: {
      transactionId: "transaction_id",
      orderId: "order_id",
      listingId: "listing_id",
      saleDate: "sale_date",
      country: "ship_country",
      city: "ship_city",
      listingTitle: "listing_title",
      itemTotal: "item_total",
      quantity: "quantity",
      itemCurrency: "item_currency",
      couponCode: "coupon_code",
    },
    selectColumns: [
      "transaction_id AS transactionId",
      "order_id AS orderId",
      "listing_id AS listingId",
      "sale_date AS saleDate",
      "sale_date_raw AS saleDateRaw",
      "listing_title AS listingTitle",
      "quantity AS quantity",
      "price AS price",
      "coupon_code AS couponCode",
      "coupon_details AS couponDetails",
      "discount_amount AS discountAmount",
      "shipping_discount AS shippingDiscount",
      "order_shipping AS orderShipping",
      "order_sales_tax AS orderSalesTax",
      "item_total AS itemTotal",
      "item_currency AS itemCurrency",
      "date_paid AS datePaid",
      "date_shipped AS dateShipped",
      "ship_country AS shipCountry",
      "ship_city AS shipCity",
      "variations AS variations",
      "order_type AS orderType",
      "listings_type AS listingsType",
      "payment_type AS paymentType",
      "vat_paid_by_buyer AS vatPaidByBuyer",
      "sku AS sku",
    ],
    filterColumns: {
      date: "sale_date",
      country: "ship_country",
      city: "ship_city",
      couponCode: "coupon_code",
      currency: "item_currency",
      orderId: "order_id",
      listingId: "listing_id",
      q: ["transaction_id", "order_id", "listing_id", "listing_title", "coupon_code", "sku"],
    },
  });
}
