import { handleTableRequest, type TableRequestContext } from "../_table";

export async function onRequestGet(context: TableRequestContext): Promise<Response> {
  return handleTableRequest(context, {
    viewName: "v_payments_canonical",
    defaultSortBy: "orderDate",
    defaultSortDir: "desc",
    sortableColumns: {
      paymentId: "payment_id",
      orderId: "order_id",
      orderDate: "order_date",
      fundsAvailableDate: "funds_available_date",
      paymentStatus: "payment_status",
      paymentCurrency: "payment_currency",
      listingCurrency: "listing_currency",
      grossAmount: "gross_amount",
      fees: "fees",
      netAmount: "net_amount",
      refundAmount: "refund_amount",
    },
    selectColumns: [
      "payment_id AS paymentId",
      "order_id AS orderId",
      "order_date AS orderDate",
      "order_date_raw AS orderDateRaw",
      "funds_available_date AS fundsAvailableDate",
      "funds_available_raw AS fundsAvailableRaw",
      "gross_amount AS grossAmount",
      "fees AS fees",
      "net_amount AS netAmount",
      "posted_gross AS postedGross",
      "posted_fees AS postedFees",
      "posted_net AS postedNet",
      "adjusted_gross AS adjustedGross",
      "adjusted_fees AS adjustedFees",
      "adjusted_net AS adjustedNet",
      "payment_currency AS paymentCurrency",
      "listing_amount AS listingAmount",
      "listing_currency AS listingCurrency",
      "exchange_rate AS exchangeRate",
      "vat_amount AS vatAmount",
      "gift_card_applied AS giftCardApplied",
      "payment_status AS paymentStatus",
      "order_type AS orderType",
      "payment_type AS paymentType",
      "refund_amount AS refundAmount",
    ],
    filterColumns: {
      date: "order_date",
      currency: "payment_currency",
      orderId: "order_id",
      status: "payment_status",
      q: ["payment_id", "order_id", "payment_status", "order_type", "payment_type"],
    },
  });
}
